### ISSUE TITLE
Some Dimensionality Reduction, Please

### ISSUE THREAD

**Issue by alizat** [Dainanahan/IDG-DREAM-Drug-Kinase-Binding-Prediction-Challenge#13]
We need some dimensionality reduction code to be added. While it would help speed up execution, another use of dimensionality reduction is to extract useful features (transform data to more useful hyperspaces) as well as implicitly reduce noise in the data. This may lead to better prediction performance!

A function called dim_red() in **ml.R** contains placeholders for some suggested dimensionality reduction functions such as: PCA, Kernel PCA, Isomap, Laplacian Eigenmaps, MDS (multidimensional scaling).

Let's hope for pleasant surprises (in the evaluation metrics results) when we get to apply these dimensionality reduction techniques to the data!

**Comment by MohammedFCIS** [comment]
done
