### ISSUE TITLE
Missing Compunds and Target Ids

### ISSUE THREAD

**Issue by MohammedFCIS** [Dainanahan/IDG-DREAM-Drug-Kinase-Binding-Prediction-Challenge#5]
Some records do not have compound ids and some do not have target ids and some do not have both, is that normal?

**Comment by alizat** [comment]
No, I do not think this is normal. The dataset was collected by crowdsourcing and was not curated as properly as some other well-known databases that store drug information.

As far as I can tell, this is a less-than-ideal dataset that has problems. Not every issue in this dataset has a good reason behind it.

**Comment by MohammedFCIS** [comment]
The issue resolved by @alizat by correcting **fread** empty strings parameter
