### ISSUE TITLE
merge all the training data into a single data frame

### ISSUE THREAD

**Issue by MohammedFCIS** [Dainanahan/IDG-DREAM-Drug-Kinase-Binding-Prediction-Challenge#9]
The following are issues in this process:

- observation count vary between the 3 data sets (in dramatic way), merging will infer a lot of NA's.
- compoundFeatures.txt is missing a single column, the compund_id 😭 
please advice

**Comment by alizat** [comment]
1. I am expecting the number of rows in each of the three data frames to be different from the other two (I would be worried if this wasn't the case). If there are NA values popping up, then maybe it is a problem from a step preceding the table join step (unless you are using the incorrect join function?). I cannot say anything more from the error description.

2. This should solve the missing column problem (unless there is an important detail you failed to mention?):
compoundFeatures <- cbind(compound_IDs, compoundFeatures)
